include: package:pedantic/analysis_options.1.9.0.yaml
analyzer:
  enable-experiment:
    - non-nullable
  exclude:
    - example/**
    - build/**
  errors:
    unused_import: warning
    unused_local_variable: warning
    public_member_api_docs: warning
linter:
  rules:
    public_member_api_docs: true