name: qrcode_flutter
description: Flutter plugin for scanning QR codes.You can customize your page by using PlatformView.Scanning Picture from path (photo album).
version: 3.0.0-nullsafety.0
# author: JSShou <xuzhongpeng.name@gmail.com>
homepage: https://github.com/xuzhongpeng/qrcode_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xzp.qrcode_flutter
        pluginClass: QrcodeFlutterPlugin 
      ios:
        pluginClass: QrcodeFlutterPlugin
